version: "3" 

services: 
  # Nombre contenedor 
  app: 
    image: platziapp 
    # Variables de entorno 
    environment: 
      MONGO_URL: "mongodb://db:27017/test"                     
    # Indica que debe iniciarse despues del contenedor "db" 
    depends_on: 
      - db 
    ports: 
      - "3000:3000" 
# Nombre contenedor 
  db: 
    image: mongo