version: "3" 

services: 
  # Nombre contenedor 
  app: 
    build: . 
    # Variables de entorno 
    environment: 
      MONGO_URL: "mongodb://db:27017/test"                     
    # Indica que debe iniciarse despues del contenedor "db" 
    depends_on: 
      - db 
    expose: 
      - "3000" 
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
# Nombre contenedor 
  db: 
    image: mongo
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"